### ISSUE TITLE
Stability of watch-fs

### ISSUE THREAD

**Issue by xeor** [linonetwo/tiddlywiki-plugins#6]
I've been looking around for a reliable way of syncing files and tiddlywiki.
Bob is what I've used till now, but it is just not reliable.. There are plenty of bug-reports on this as you know, including some that awaits upstream changes to tiddlywiki and so on..

I tried out `watch-fs`, and it seams to do exactly what I want, and it looks fairly stable as well.

Is it? Have you had any big problems when using it? It is a really different approach than bob, and frankly, the sync-time is not that big of a deal.. So is there any reason not to just use `watch-fs`?

**Comment by linonetwo** [comment]
Hi, thanks for the tryout, the basic sync logic is OK, I'm using it everyday in my TG-Note.

But there surely have some bug https://github.com/tiddly-gittly/TiddlyGit-Desktop/issues/32 , I fix those bugs every weekend if I encounter some in my weekdays.

I tried to use bob before, but it don't work weel with FileSystemPath, so I choose to make my own. It is still in beta.

**Comment by xeor** [comment]
That is great! I will start using this plugin as well and report back any bugs :)
The only reason I looked into bob was to get file-sync, so this is perfect.

Keep up the great work! And thanks for making this!
